version: '3.8'

services:
  backend:
    image: demande-back
    container_name: demande-back
    ports:
      - "8081:8081"

  frontend:
    image: demande-front
    container_name: demande-front
    ports:
      - "4200:80"
